name: RelicHunt
version: 0.1
main: io.github.erickeis.relichunt.RelicHunt
api-version: '1.18'

commands:
  relichunt:
    description: This is the base command for the plugin
    usage: /<command>
    permission: relichunt.admin